input SendGiftPayload {
  targetId: ID!
  authorId: ID!
  resourceType: ResourceType!
  amount: Int!
}

type GiftMutation {
  # Отправка подарков
  send(payload: SendGiftPayload!): Gift!
}

type Mutation {
  # Мутации подарков
  gift: GiftMutation
}
