mutation sendGift($type: ResourceType!, $amount: Int!, $authorId: ID!, $targetId: ID!) {
  gift {
    send(payload: { resourceType: $type, amount: $amount, authorId: $authorId, targetId: $targetId }) { amount }
  }
}
