query fetchPlayer($id: ID!) {
  player(id: $id) {
    id
    username
  }
}

query fetchPlayers {
  players {
    id
    username
  }
}

query fetchResources($id: ID!) {
  resources(id: $id) {
    resourceType
    amount
  }
}
query fetchGifts($id: ID!) {
  gifts(filter: { targetIds: [$id] }) {
    resourceType
    amount
    createdAt
    authorId
    targetId
  }
}

query fetchLatestGifts {
  latestGifts {
    resourceType
    amount
    createdAt
    authorId
    targetId
  }
}
